### ISSUE TITLE
2017年01月11日 光明頂 檔案疑似不全

### ISSUE THREAD

**Issue by tannx** [YuetWanLauSeng/881903#2]
下載到的檔案大小是25.2Mb 長度34分57秒

播放到結尾時發現節目好像還未完就沒了。

**Comment by YuetWanLauSeng** [comment]
你好，經核查節目時長為36:40，估計因百度雲服務器問題所致，建議可嘗試使用MediaFire下載：
http://www.mediafire.com/file/x3gj8ytt2b40c30/Summit.2017-01-11.mp3

2017-01-12 3:48 GMT+08:00 tannx <notifications@github.com>:

**Comment by tannx** [comment]
Thank you.
